apiVersion: v1
data:
  cacerts.pem: XXX
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"kind":"Secret","apiVersion":"v1","metadata":{"name":"tls-ca","namespace":"cattle-system","creationTimestamp":null},"data":{"cacerts.pem":"XXX"}}
    kubed.appscode.com/sync: "" # Copy the secret to all existing and new namespaces
    # kubed.appscode.com/sync: "cert-manager-tls=sandbox" # Sync certificate to matching namespaces
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: ""  # Control destination namespaces
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true" # Auto create reflection for matching namespaces
    reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "" # Control auto-reflection namespaces
  creationTimestamp: null
  name: tls-ca
  namespace: cattle-system
