apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crd-access
rules:
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list", "watch"]

---

apiVersion: management.cattle.io/v3
context: cluster
description: ''
displayName: Company Member
kind: RoleTemplate
metadata:
  name: company-member
roleTemplateNames:
  - cluster-member
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]