grafana:
  adminPassword: password
  grafana.ini:
    server:
      domain: "ml-cluster.domaine.de"
      root_url: "%(protocol)s://%(domain)s/grafana/"
      serve_from_sub_path: "true"
    dashboards:
      default_home_dashboard_path: /tmp/dashboards/gpu-dashboard.json
  ingress:
    enabled: true
    hosts:
      - ml-cluster.domaine.de
    path: "/grafana"
    pathType: Prefix # ImplementationSpecific
  persistence:
    type: pvc
    enabled: true
    size: 10Gi